### ISSUE TITLE
NRPA复现问题

### ISSUE THREAD

**Issue by QinghaoSun** [TianHongTao/Recommendation-System-Graduation-Design#5]
您好，非常感谢您开源代码。我是一名初学者，NRPA复现代码运行生成相应文件时总是出现错误，能否帮忙调试一下。
Traceback (most recent call last):
  File "D:\ID-DAML-master\Utils\AWS.py", line 149, in <module>
    main(DATA_PATH_MUSIC)
  File "D:\ID-DAML-master\Utils\AWS.py", line 43, in main
    data_test, data_train = save_rating(data, path)
  File "D:\ID-DAML-master\Utils\AWS.py", line 48, in save_rating
    data = numerize(data)
  File "D:\ID-DAML-master\Utils\AWS.py", line 143, in numerize
    data['user_id'] = list(uid)
  File "D:\ID-DAML-master\Utils\AWS.py", line 140, in <lambda>
    uid = map(lambda x: user2id[x], data['user_id'])
KeyError: 'A2TYZ821XXK2YZ'

**Comment by TianHongTao** [comment]
看着是你的map函数里面的data['user_id']里面的 A2TYZ821XXK2YZ 这个值没在user2id里面造成的，你check一下数据。

**Comment by TianHongTao** [comment]
> 您好，非常感谢您开源代码。我是一名初学者，NRPA复现代码运行生成相应文件时总是出现错误，能否帮忙调试一下。 Traceback (most recent call last): File "D:\ID-DAML-master\Utils\AWS.py", line 149, in main(DATA_PATH_MUSIC) File "D:\ID-DAML-master\Utils\AWS.py", line 43, in main data_test, data_train = save_rating(data, path) File "D:\ID-DAML-master\Utils\AWS.py", line 48, in save_rating data = numerize(data) File "D:\ID-DAML-master\Utils\AWS.py", line 143, in numerize data['user_id'] = list(uid) File "D:\ID-DAML-master\Utils\AWS.py", line 140, in uid = map(lambda x: user2id[x], data['user_id']) KeyError: 'A2TYZ821XXK2YZ'

看着是你的map函数里面的data['user_id']里面的 A2TYZ821XXK2YZ 这个值没在user2id里面造成的，你check一下数据。

**Comment by QinghaoSun** [comment]
您好，我上述问题我已经解决，非感谢您的建议，但我在运行NRPA文件时又出现了这样的错误，我多次更改版本，基本上与您的版本相同，但仍旧无法解决，希望您能给一些意见。
Traceback (most recent call last):
  File "D:\ID-DAML-master\reappearance\NRPA.py", line 360, in <module>
    main(path)
  File "D:\ID-DAML-master\reappearance\NRPA.py", line 208, in main
    word_model  = Word2Vec.load("D:\\Resource\\Datas\\Digital_Music_5.model")
  File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\models\word2vec.py", line 1330, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\models\base_any2vec.py", line 1244, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\models\base_any2vec.py", line 603, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\utils.py", line 426, in load
    obj = unpickle(fname)
  File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\utils.py", line 1384, in unpickle
    return _pickle.load(f, encoding='latin1')
TypeError: __randomstate_ctor() takes from 0 to 1 positional arguments but 2 were given

**Comment by QinghaoSun** [comment]
您好，上述问题我已经解决，非常感谢您的建议，但我在运行NRPA文件时又出现了这样的错误，我多次更改版本，基本上与您的版本相同，但仍旧无法解决，希望您能给一些意见。
Traceback (most recent call last):
File "D:\ID-DAML-master\reappearance\NRPA.py", line 360, in
main(path)
File "D:\ID-DAML-master\reappearance\NRPA.py", line 208, in main
word_model = Word2Vec.load("D:\Resource\Datas\Digital_Music_5.model")
File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\models\word2vec.py", line 1330, in load
model = super(Word2Vec, cls).load(*args, **kwargs)
File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\models\base_any2vec.py", line 1244, in load
model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\models\base_any2vec.py", line 603, in load
return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\utils.py", line 426, in load
obj = unpickle(fname)
File "D:\anaconda3\envs\pytorchNRPA\lib\site-packages\gensim\utils.py", line 1384, in unpickle
return _pickle.load(f, encoding='latin1')
TypeError: __randomstate_ctor() takes from 0 to 1 positional arguments but 2 were given
